### PR TITLE
new layout test

### PR DESCRIPTION
**Pull request by bilalze**
my changes for the new layout testing

### CODE REVIEW

**Comment by michiexile** [comment]
I have merged the PR. However, looking through it I notice that your header and footer layouts hardcode everything, whereas I built the theme to work extensively with a `_data` directory to give easy edits to header and footer content. We should look at refactoring to YaML-specifications generating the header and footers.

One underlying red thread in my design thinking here is to separate **maintaining website contents** from **maintaining website design**. Only one of these two tasks should require significant knowledge of HTML, and by using scaffolds that take Markdown and YaML inputs, the content maintainers only really will end up needing to edit plain text files with relatively easy markup.

**Comment by bilalze** [comment]
Agreed. Will fix. You idea sounds good.

**Comment by bilalze** [comment]
ive made all the changes you suggested. but i can create a pull request for
some reason. If you can merge that would be great . "Pull request creation
failed. Validation failed: was submitted too quickly"

Best,

**Comment by bilalze** [comment]
changes are made to test, header test and footer test. Also new yaml files
required are created.

**Pull request merged**
